### ISSUE TITLE
eQuaSmart's word spacing

### ISSUE THREAD

**Issue by karlspf** [markplnivo/equasmart#9]
![Untitled](https://github.com/user-attachments/assets/1422542a-4cc9-4fe2-a9ef-107f0fc74df9)

1. Please change "eQua Smart" to "eQuaSmart".
2. Please change "eQua Smart" to "eQuaSmart".
3. Please change "EQUA SMART" to "eQuaSmart".

**Comment by markplnivo** [comment]
fixed thank you
